<a href="https://colab.research.google.com/github/jashinspires/Numpyknowledge/blob/main/numpybasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**
- NumPy is the fundamental package for scientific computing in python. It is a python library that provides a multidimensional array object , various derivved objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays , including mathematical , logical , shape manipulation , sorting , selecting , I/O , discrete Fourier Transforms , basic linear algebra , basic statistical operations , random simulation and much more.

- At the core of NumPy package , is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

## **NUMPY ARRAYS VS PYTHON SEQUENCES**
- Numpy arrays have a fixed size at creation , unlike python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
- The elements in a Numpy array are all required to be of the same data type , and thus will be the same size in memory.
- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically such operations are executed more efficiently and with less code than is possible using Python's built-in sequences.
- A growing plethora of scientific and mathematical Python-based packages are using packages are using NumPy arrays ; though these typically support Pythonic-sequence input , they convert such input into Numpy arrays prior to processing , and they often output NumPy arrays.


In [1]:
import numpy as np
a = np.array([1,3,4,5])
print(a)

[1 3 4 5]


In [2]:
type(a)

numpy.ndarray

In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c = np.array([[[1,2,3],[4,5,6]],[[3,45,8],[21,32,1]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 3 45  8]
  [21 32  1]]]


In [5]:
type(c)

numpy.ndarray

In [6]:
k = np.array([1,2,3], dtype= float)
print(k)

[1. 2. 3.]


In [7]:
np.arange(1,11,2) # same as loops (start , end , increment)

array([1, 3, 5, 7, 9])

In [8]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((3,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.random.random((4,5))

array([[0.12401164, 0.32539047, 0.35090658, 0.82456691, 0.00144298],
       [0.85035578, 0.81076371, 0.33070928, 0.94197517, 0.95369464],
       [0.28650116, 0.54358034, 0.68776226, 0.52493273, 0.35120267],
       [0.91217466, 0.94489098, 0.65077069, 0.80489677, 0.11326842]])

In [12]:
np.linspace(-10,10,10,dtype = int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [13]:
np.identity(10) # identity matrix of 10 by 10

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [14]:
arr1 = np.arange(8)
arr2 = np.arange(8,dtype=float).reshape(2,4)
arr3 = np.arange(8).reshape(2,2,2)

In [15]:
arr1.ndim#tells the dimensionality of an array
arr3.ndim

3

In [16]:
arr1.shape

(8,)

In [17]:
arr2.shape

(2, 4)

In [18]:
arr3.shape # here (2,2,2) -> first 2 says there are two 2d arrays , then second two is no of rows and last 2 is no of columns

(2, 2, 2)

In [19]:
print(arr3.size)

8


In [20]:
arr1.itemsize #size of a single value in bytes , here 4 bytes

8

In [21]:
print(arr3.dtype) # tells the data type

int64


In [22]:
arr3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

#  **Array Operations**


In [23]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [24]:
a1*2 # Scalar Operations

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [25]:
a2 == 15 #relational

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [26]:
# Vector Operations
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [27]:
# Array Funcions
k1 = np.random.random((4,4))
k1

array([[0.04467458, 0.15384299, 0.33646979, 0.82571386],
       [0.37708544, 0.14056186, 0.61915367, 0.81934594],
       [0.23876534, 0.24947149, 0.6478556 , 0.7999442 ],
       [0.82433457, 0.39077453, 0.88263791, 0.04135564]])

In [28]:
# max/min/sum/prod
np.prod(k1)

np.float64(1.8636484239079616e-08)

In [29]:
np.prod(k1, axis = 0)

array([0.0033157 , 0.00210811, 0.11912566, 0.02238161])

In [30]:
k2 = np.array(([1,1,1],[0,0,0],[1,1,1]))

In [31]:
k2

array([[1, 1, 1],
       [0, 0, 0],
       [1, 1, 1]])

In [32]:
np.prod(k2, axis = 1 , dtype = int)

array([1, 0, 1])

In [33]:
# MEAN/MEDIAN/std/var
np.mean(k1,axis=1)

array([0.3401753 , 0.48903673, 0.48400916, 0.53477566])

In [34]:
np.median(k1)

np.float64(0.3839299825668636)

In [35]:
# Dot Product
d1 = np.arange(12).reshape(3,4)
d2 = np.arange(13,25).reshape(4,3)

In [36]:
np.dot(d1,d2)

array([[120, 126, 132],
       [400, 422, 444],
       [680, 718, 756]])

In [37]:
# Indexing and Slicing

I1 = np.arange(12)
I2 = np.arange(12).reshape(3,4)
I3 = np.arange(27).reshape(3,3,3)

In [38]:
I3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [39]:
I3[1,1,0]

np.int64(12)

In [40]:
I1[2:5:2]

array([2, 4])

In [41]:
I2[0,:2]
I2[:,2]

array([ 2,  6, 10])

In [42]:
I2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
I2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [44]:
I2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [45]:
I2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [46]:
I2[1,::3]

array([4, 7])

In [47]:
I3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [48]:
I3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [49]:
I3[0,1,:]

array([3, 4, 5])

In [50]:
I3[1,:,1]

array([10, 13, 16])

In [51]:
I3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [52]:
I3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [53]:
I3[0::2 ,0,0::2]

array([[ 0,  2],
       [18, 20]])

In [54]:
# Iterator
for i in np.nditer(I3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [55]:
np.transpose(I2) #or I2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [56]:
# ravel converts nd to 1d

In [57]:
I3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [58]:
# Stacking
np.hstack((I2,I2))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [59]:
np.vstack((I2,I2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
np.hsplit(I2,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [61]:
np.vsplit(I2,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]